disk= "./disk2.vdi"
hostname= "ose-aio"
domain= "rhose.org"
dns= "true"
dns_server="10.211.55.45"
ip_master="192.168.150.2"


require 'vagrant-registration'

Vagrant.configure(2) do |config|
  config.vm.box = "rhel-7.1"
  config.vm.hostname = hostname

  #config.registration.skip=true
  config.registration.subscriber_username = ENV['SUB_USERNAME']
  config.registration.subscriber_password = ENV['SUB_PASSWORD']

  #config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 8443, host: 8443
  config.vm.network "private_network", ip: ip_master

  #config.vm.provision "file", source: "scripts/hosts", destination: "~"
  
  config.vm.provision "shell", name: "Output shell environment variables", args: [disk, hostname, domain, ip_master, dns, dns_server], inline: <<-SHELL
    echo "disk: $1"
    echo "hostname: $2"
    echo "domain: $3"
    echo "ip_master: $4"
    echo "dns: $5"
    echo "dns_server: $6"
  SHELL
  
  config.vm.provision "shell", name: "Create new etc hosts file", args: [hostname, domain, ip_master], inline: <<-SHELL
    echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
    echo "::1         localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
    echo "$3 $1.$2 $1" >> /etc/hosts
  SHELL

  config.vm.provision "shell", name: "Prepare OSE environment", args: [hostname, domain], path: "scripts/prep_ose.sh"
  #if dns == "true"
  #  config.vm.provision "shell", args: dns_server, path: "scripts/update_network.sh"
  #else
    #config.vm.provision "shell", inline: ">> NO DNS REFERENCED"
  #  puts ">> NO DNS REFERENCED"
  #end
  config.vm.provision "shell", name: "Install and configure OSE", args: [hostname, domain, ip_master, dns, dns_server], path: "scripts/install_ose.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    vb.memory = 2048
    unless File.exist?(disk)
      vb.customize ["createhd", "--filename", disk, "--size", "8192"]
    end
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", disk]
  end

end
